'use strict'

export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_INPUT_PASSWORD_CHANGED = 'USER_INPUT_PASSWORD_CHANGED';
export const USER_OPEN_LOGIN_FORM = 'USER_OPEN_LOGIN_FORM';
export const USER_CLOSE_LOGIN_FORM = 'USER_CLOSE_LOGIN_FORM';

export const CHANGE_USER_DATE_FORMAT = 'CHANGE_USER_DATE_FORMAT';

export const USER_INPUT_NAME_CHANGED = 'USER_INPUT_NAME_CHANGED';
export const USER_INPUT_FAIL_NAME = 'USER_INPUT_FAIL_NAME';
export const USER_INPUT_SURNAME_CHANGED = 'USER_INPUT_SURNAME_CHANGED';
export const USER_INPUT_FAIL_SURNAME = 'USER_INPUT_FAIL_SURNAME';
export const USER_INPUT_BIRTH_DATE_CHANGED = 'USER_INPUT_BIRTH_DATE_CHANGED';
export const USER_INPUT_FAIL_BIRTH_DATE = 'USER_INPUT_FAIL_BIRTH_DATE';
export const USER_INPUT_FAIL_MONTH = 'USER_INPUT_FAIL_MONTH';
export const USER_INPUT_FAIL_DATE_FORMAT = 'USER_INPUT_FAIL_DATE_FORMAT';
export const USER_INPUT_FAIL_FEBRUARY_DAY = 'USER_INPUT_FAIL_FEBRUARY_DAY';
export const USER_INPUT_FAIL_MONTH_30 = 'USER_INPUT_FAIL_MONTH_30';
export const USER_INPUT_FAIL_DAY = 'USER_INPUT_FAIL_DAY';
export const USER_INPUT_FAIL_YEAR = 'USER_INPUT_FAIL_YEAR';
export const USER_INPUT_EMAIL_CHANGED = 'USER_INPUT_EMAIL_CHANGED';
export const USER_INPUT_FAIL_EMAIL = 'USER_INPUT_FAIL_EMAIL';
export const USER_INPUT_FAIL_EMAIL_FORMAT = 'USER_INPUT_FAIL_EMAIL_FORMAT';
export const USER_INPUT_PHONE_CHANGED = 'USER_INPUT_PHONE_CHANGED';
export const USER_INPUT_FAIL_PHONE = 'USER_INPUT_FAIL_PHONE';
export const USER_INPUT_FAIL_PHONE_FORMAT = 'USER_INPUT_FAIL_PHONE_FORMAT';
export const USER_INPUT_REGPASSWORD_CHANGED = 'USER_INPUT_REGPASSWORD_CHANGED';
export const USER_INPUT_FAIL_REGPASSWORD = 'USER_INPUT_REGPASSWORD';
export const USER_INPUT_FAIL_REGPASSWORD_LENGHT = 'USER_INPUT_REGPASSWORD_LENGHT';
export const USER_INPUT_FAIL_REGPASSWORD_FORMAT = 'USER_INPUT_FAIL_REGPASSWORD_FORMAT';
export const USER_INPUT_AVATAR = 'USER_INPUT_AVATAR';

export const USER_TRY_TO_REGISTER = 'USER_TRY_TO_REGISTER';
export const USER_SUCCESS_REGISTER = 'USER_SUCCESS_REGISTER';
export const USER_FAIL_REGISTER = 'USER_FAIL_REGISTER';

export const USER_TRY_TO_LOG_IN = 'USER_TRY_TO_LOG_IN';
export const USER_SUCCESS_LOG_IN = 'USER_SUCCESS_LOG_IN';
export const USER_FAIL_LOG_IN = 'USER_FAIL_LOG_IN';
export const USER_TRY_TO_LOG_OUT = 'USER_TRY_TO_LOG_OUT';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_PERSONAL_LOADING = 'GET_PERSONAL_LOADING';
export const GET_PERSONAL_SUCCESS = 'GET_PERSONAL_SUCCESS';
export const GET_PERSONAL_FAIL = 'GET_PERSONAL_FAIL';
// изменение личных данных
export const USER_TRY_TO_CHANGE_INFO = 'USER_TRY_TO_CHANGE_INFO';
export const USER_SUCCESS_CHANGE_INFO = 'USER_SUCCESS_CHANGE_INFO';
export const USER_FAIL_CHANGE_INFO = 'USER_FAIL_CHANGE_INFO';

// получение информации о публикациях
export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
// создание новой публикации
export const POST_INPUT_TITLE = 'POST_INPUT_TITLE';
export const POST_TITLE_INVALID = 'POST_TITLE_INVALID';
export const POST_INPUT_TYPE = 'POST_INPUT_TYPE';
export const POST_INPUT_TEXT = 'POST_INPUT_TEXT';
export const POST_TEXT_INVALID = 'POST_TEXT_INVALID';
export const POST_TRY_TO_CREATE = 'POST_TRY_TO_CREATE';
export const POST_SUCCESS_CREATE = 'POST_SUCCESS_CREATE';
export const POST_FAIL_CREATE = 'POST_FAIL_CREATE';
